### ISSUE TITLE
New Plugin Configuration steps

### ISSUE THREAD

**Issue by nshvr** [kobsio/kobs#207] opened 2021-11-18 14:58 UTC
Hi Team,

Kindly share configuration documents with steps to configure the new Plugin which will be useful to configure and test the new plugin.
We implemented a new plugin but we are not able to integrate it with kobs. Maybe we are missing some configuration ?.Please share detailed configuration steps. 

Thanks,
Harry

**Comment by ricoberger** [comment] 2021-11-18 18:19
Hi @nshvr, information about how to develop a plugin can be found in the following file [develop-a-plugin.md](https://github.com/kobsio/kobs/blob/2cb7362a943682cc142321ac6f35c7590e4d6264/docs/contributing/develop-a-plugin.md).

To integrate your plugin you can use the [kobsio/app](https://github.com/kobsio/app) template. More information on how to add a plugin there can be found here: https://kobs.io/contributing/using-the-kobsio-app/

I also create a plugin, to rework these parts of the documentation, please let me know what is still missing so I can add the missing parts in #208.

**Comment by AkshayDubey29** [comment] 2021-11-19 03:28
@ricoberger It seems something is missing in the document after adding in index.tsx and in plugins.GO we are getting the below error:

![image](https://user-images.githubusercontent.com/14831408/142559912-d398566e-f8d3-4c84-a941-5a051dfa740a.png)



```Go
package plugins

import (
	"net/http"

	"github.com/kobsio/kobs/pkg/api/clusters"
	"github.com/kobsio/kobs/pkg/api/plugins/plugin"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/render"

	// Import all plugins, which should be used with the kobs instance. By default this are all first party plugins from
	// the plugins folder.
	//"github.com/kobsio/kobs/plugins/applications"
	//"github.com/kobsio/kobs/plugins/clickhouse"
	//"github.com/kobsio/kobs/plugins/dashboards"
	//"github.com/kobsio/kobs/plugins/elasticsearch"
	//"github.com/kobsio/kobs/plugins/flux"
	//"github.com/kobsio/kobs/plugins/jaeger"
	//"github.com/kobsio/kobs/plugins/kiali"
	//"github.com/kobsio/kobs/plugins/markdown"
	//"github.com/kobsio/kobs/plugins/opsgenie"
	//"github.com/kobsio/kobs/plugins/prometheus"
	//"github.com/kobsio/kobs/plugins/resources"
	//"github.com/kobsio/kobs/plugins/rss"
	//"github.com/kobsio/kobs/plugins/sql"
	//"github.com/kobsio/kobs/plugins/teams"
	//"github.com/kobsio/kobs/plugins/users"
	"github.com/kobsio/app/pkg/plugins/helloworld"
        "github.com/AkshayDubey29/plugin-splunk/app/pkg/splunk"
)

// Config holds the configuration for all plugins. We have to add the configuration for all the imported plugins.
type Config struct {
	//Applications  applications.Config  `json:"applications"`
	//Clickhouse    clickhouse.Config    `json:"clickhouse"`
	//Dashboards    dashboards.Config    `json:"dashboards"`
	//Elasticsearch elasticsearch.Config `json:"elasticsearch"`
	//Flux          flux.Config          `json:"flux"`
	//Jaeger        jaeger.Config        `json:"jaeger"`
	//Kiali         kiali.Config         `json:"kiali"`
	//Markdown      markdown.Config      `json:"markdown"`
	//Opsgenie      opsgenie.Config      `json:"opsgenie"`
	//Prometheus    prometheus.Config    `json:"prometheus"`
	//Resources     resources.Config     `json:"resources"`
	//RSS           rss.Config           `json:"rss"`
	//SQL           sql.Config           `json:"sql"`
	//Teams         teams.Config         `json:"teams"`
	//Users         users.Config         `json:"users"`
        splunkPlugin    splunk.Config        `json:"splunk"`

	HelloWorld helloworld.Config `json:"helloworld"`
}

// Router implements the router for the plugins package. This only registeres one route which is used to return all the
// configured plugins.
type Router struct {
	*chi.Mux
	plugins *plugin.Plugins
}

// getPlugins returns all registered plugin instances.
func (router *Router) getPlugins(w http.ResponseWriter, r *http.Request) {
	render.JSON(w, r, router.plugins)
}

// Register is used to register all api routes for plugins.
func Register(clusters *clusters.Clusters, config Config) chi.Router {
	router := Router{
		chi.NewRouter(),
		&plugin.Plugins{},
	}

	router.Get("/", router.getPlugins)

	// Register all plugins
	//router.Mount(resources.Route, resources.Register(clusters, router.plugins, config.Resources))
	//router.Mount(applications.Route, applications.Register(clusters, router.plugins, config.Applications))
	//router.Mount(teams.Route, teams.Register(clusters, router.plugins, config.Teams))
	//router.Mount(users.Route, users.Register(clusters, router.plugins, config.Users))
	//router.Mount(dashboards.Route, dashboards.Register(clusters, router.plugins, config.Dashboards))
	//router.Mount(prometheus.Route, prometheus.Register(clusters, router.plugins, config.Prometheus))
	//router.Mount(elasticsearch.Route, elasticsearch.Register(clusters, router.plugins, config.Elasticsearch))
	//router.Mount(jaeger.Route, jaeger.Register(clusters, router.plugins, config.Jaeger))
	//router.Mount(kiali.Route, kiali.Register(clusters, router.plugins, config.Kiali))
	//router.Mount(flux.Route, flux.Register(clusters, router.plugins, config.Flux))
	//router.Mount(opsgenie.Route, opsgenie.Register(clusters, router.plugins, config.Opsgenie))
	//router.Mount(clickhouse.Route, clickhouse.Register(clusters, router.plugins, config.Clickhouse))
	//router.Mount(sql.Route, sql.Register(clusters, router.plugins, config.SQL))
	//router.Mount(markdown.Route, markdown.Register(clusters, router.plugins, config.Markdown))
	//router.Mount(rss.Route, rss.Register(clusters, router.plugins, config.RSS))
        router.Mount(splunk.Route, splunk.Register(clusters, router.plugins, config.Splunk))
	router.Mount(helloworld.Route, helloworld.Register(clusters, router.plugins, config.HelloWorld))

	return router
}


```tsx
import React from 'react';
import ReactDOM from 'react-dom';

import './index.css';

import { App } from '@kobsio/plugin-core';

import helloWorldPlugin from './plugins/helloworld';
import splunkPlugin from './plugins/splunk';

ReactDOM.render(
  <React.StrictMode>
    <App plugins={{
      ...resourcesPlugin,
      ...teamsPlugin,
      ...usersPlugin,
      ...applicationsPlugin,
      ...dashboardsPlugin,
      ...prometheusPlugin,
      ...elasticsearchPlugin,
      ...jaegerPlugin,
      ...kialiPlugin,
      ...fluxPlugin,
      ...opsgeniePlugin,
      ...markdownPlugin,
      ...rssPlugin,
      ...clickhousePlugin,
      ...sqlPlugin,
      ...helloWorldPlugin,
      ...splunkPlugin,
    }} />
  </React.StrictMode>,
  document.getElementById('root')
);

**Comment by AkshayDubey29** [comment] 2021-11-19 04:34
![image](https://user-images.githubusercontent.com/14831408/142565416-fc6ff010-5c94-4cd8-a6a9-81818070b9f1.png)

Tried to add explicitly but didn't work, is there anything needs to be added?

**Comment by ricoberger** [comment] 2021-11-19 09:51
Hi @AkshayDubey29, I think the import path in the `plugins.go` is wrong, can you try the following please:

- In `cmd/kobs/plugins/plugins.go` use `github.com/kobsio/app/pkg/plugins/splunk` as import.
- In `pkg/plugins/splunk/splunk.go` use `github.com/kobsio/app/pkg/plugins/splunk/pkg/instance` as import.

**Comment by AkshayDubey29** [comment] 2021-11-19 11:18
Do you know why are we getting this error now?
We are using https://github.com/kobsio/app template to build the plugin,

16:40:47 $ react-scripts build
16:40:50 Creating an optimized production build...
16:43:29 Failed to compile.
16:43:29 
16:43:29 /kobs/app/src/plugins/splunk/components/page/PageToolbar.tsx
16:43:29 TypeScript error in /kobs/app/src/plugins/splunk/components/page/PageToolbar.tsx(63,9):
16:43:29 Property 'time' is missing in type '{ timeEnd: number; timeStart: number; }' but required in type 'IPluginTimes'.  TS2741
16:43:29 
16:43:29     61 |         ...tmpData,
16:43:29     62 |         fields: fields,
16:43:29   > 63 |         times: { timeEnd: timeEnd, timeStart: timeStart },
16:43:29        |         ^
16:43:29     64 |       });
16:43:29     65 |     }
16:43:29     66 |
16:43:29

**Comment by ricoberger** [comment] 2021-11-19 11:55
There was a breaking change introduced in https://github.com/kobsio/kobs/pull/181, which isn't released yet.

To fix this issue you can add the `time` property or you can wait for the next release v0.7.0 where this property is removed.

I'm currently working on another plugin, after that I can trigger a new release. Maybe I can get this done today in the afternoon.

**Comment by ricoberger** [comment] 2021-11-19 22:17
I release v0.7.0 and updated the [kobsio/app](https://github.com/kobsio/app) template. So if you update all your packages to v0.7.0 the `times` property shouldn't be required anymore.

**Comment by AkshayDubey29** [comment] 2021-11-20 03:49
Thank you :)

I tried but got the below error, might be I am missing some config


![image](https://user-images.githubusercontent.com/14831408/142713483-c3de5de5-015d-460d-86a4-bcd200873f95.png)

**Comment by ricoberger** [comment] 2021-11-20 22:38
Did you run `go mod tidy` in the root of your repository?

If you can provide me a link to your repository I can also have a detailed look if you want.

**Comment by AkshayDubey29** [comment] 2021-11-21 04:19
I sincerely apologize @ricoberger  But we are building this to internal network which I suppose you cannot access :(

We are trying to build the whole application internal to our network, but facing issues

**Comment by AkshayDubey29** [comment] 2021-11-21 18:27
@ricoberger Any idea why are we getting this error, we have copied this folder https://github.com/kobsio/kobs/tree/main/plugins/core to https://github.com/kobsio/app/tree/main/app/src/plugins to build our own version of kobs:

![image](https://user-images.githubusercontent.com/14831408/142774433-f1524c15-79e2-44dc-8698-4cdb5356123c.png)

**Comment by ricoberger** [comment] 2021-11-21 20:46
I think it would be better to move the content from the https://github.com/kobsio/kobs/tree/main/plugins/core/src folder to a folder named https://github.com/kobsio/app/tree/main/app/src/plugins/core. So that the https://github.com/kobsio/kobs/blob/main/plugins/core/src/index.ts file is then at https://github.com/kobsio/app/blob/main/app/src/plugins/core/index.ts.

Then you can import everything from the core package via `import { <COMPONENT> } from './plugins/core';`.

Please keep in mind that you also have to add all the dependencies from https://github.com/kobsio/kobs/blob/main/plugins/core/package.json to your `package.json`.

**Comment by AkshayDubey29** [comment] 2021-11-22 02:21
You mean to say in this package.json https://github.com/kobsio/app/blob/main/app/package.json right?

**Comment by AkshayDubey29** [comment] 2021-11-22 02:46
Might be this is happening because of dependency only:

![image](https://user-images.githubusercontent.com/14831408/142793585-be2f45b9-1d6a-4ddb-b1bc-d6cd3200eae3.png)

**Comment by AkshayDubey29** [comment] 2021-11-22 02:51
We have put the version which we want to build, can you have a look and let us know what are we missing?

https://github.com/AkshayDubey29/internal-kobs

**Comment by AkshayDubey29** [comment] 2021-11-22 14:43
![image](https://user-images.githubusercontent.com/14831408/142880988-ffc01f95-8d4a-48c4-bd76-9090f8fbb9c9.png)

Any Missing Part, trying to build istio plugin.

**Comment by ricoberger** [comment] 2021-11-22 19:59
> You mean to say in this package.json https://github.com/kobsio/app/blob/main/app/package.json right?

Yes correct.

> Might be this is happening because of dependency only

This looks like, you also have to create a `typings.d.ts` file in the https://github.com/kobsio/app/blob/main/app/src folder, with the content of the following file https://github.com/kobsio/kobs/blob/main/typings.d.ts. (When you created this file the https://github.com/kobsio/app/blob/main/app/typings.d.ts file can/must be deleted).

This should also fix the `cytoscape-node-html-label` is not a module error.

**Comment by AkshayDubey29** [comment] 2021-11-23 01:41
Thanks @ricoberger , let me check

**Comment by AkshayDubey29** [comment] 2021-11-23 07:38
Hi @ricoberger Do you know which component I am missing

![image](https://user-images.githubusercontent.com/14831408/142986095-08572c99-4094-4d3b-969d-1377f5f0b418.png)


If you will see in above image cluster ID is getting populated but when I pulled internal image, Cluster ID and namespace is not getting populated.

**Comment by ricoberger** [comment] 2021-11-23 07:45
Hi @AkshayDubey29 the cluster and namespace is coming from the `ClustersContextProvider` component. Which is set in the following file https://github.com/kobsio/kobs/blob/main/plugins/core/src/components/app/App.tsx

**Comment by AkshayDubey29** [comment] 2021-11-23 08:33
Even If I am going inside I am seeing Plugin not found but I have added the same:

![image](https://user-images.githubusercontent.com/14831408/142991949-9b9e74ec-bf26-4d8f-bf31-65af1cce5f54.png)


![image](https://user-images.githubusercontent.com/14831408/142992003-6bfde93c-c34d-4996-b154-73175c02a2ce.png)


![image](https://user-images.githubusercontent.com/14831408/143020330-873991be-d16d-4db5-8e29-8bb28a774ea8.png)

**Comment by AkshayDubey29** [comment] 2021-11-23 09:32
@ricoberger Can you tell me where exactly we need to copy tsconfig.json and tsconfig.esm.json in https://github.com/kobsio/app/app/src/plugin/<pluginName> or in https://github.com/kobsio/app/pkg/plugin/<pluginName>


So for example for the Prometheus plugin if we will take in from default that case where do we need to put https://github.com/kobsio/kobs/blob/main/plugins/prometheus/tsconfig.json 

As I am noticing we are unable to read https://github.com/kobsio/kobs/blob/main/plugins/core/src/components/app/App.tsx and the above issue is happening because of tsconfig.json and tsconfig.esm.json

**Comment by ricoberger** [comment] 2021-11-23 19:13
@AkshayDubey29 the `tsconfig.json` and `tsconfig.esm.json` file for each plugin can be deleted, when you copy the whole code of a plugin.

For the Prometheus example it should be enough if you copy the content from https://github.com/kobsio/kobs/tree/main/plugins/prometheus/src into https://github.com/kobsio/app/tree/main/app/src/plugins/prometheus and add the dependencies from https://github.com/kobsio/kobs/blob/main/plugins/prometheus/package.json to your package.json. 

For the Go part you can then [prometheus.go](https://github.com/kobsio/kobs/blob/main/plugins/prometheus/prometheus.go) file and the [pkg/instance](https://github.com/kobsio/kobs/tree/main/plugins/prometheus/pkg/instance) folder into a new folder https://github.com/kobsio/app/tree/main/pkg/plugins/prometheus

It is possible that you have to adjust some of the import paths in the plugin yourself.

I'm not sure how good this will work, because it might be possible that there are dependencies between plugin and the case of copying the whole code of plugins is not really covered/intended. A better way would be to add the plugins via the NPM packages and for Go via Git like it is done in the [kobsio/app](https://github.com/kobsio/app) example.

> Even If I am going inside I am seeing Plugin not found but I have added the same:

For this error, can you check if the `/api/plugins` and `/api/clusters` does return some data, maybe the problem is within your modification of the Go code and not within the frontend.

**Comment by AkshayDubey29** [comment] 2021-11-24 04:37
@ricoberger  /api/plugins and /api/clusters both are returning correct values.

![image](https://user-images.githubusercontent.com/14831408/143175779-14784878-c00a-4ec3-af4e-b40f9cf1901b.png)

![image](https://user-images.githubusercontent.com/14831408/143175802-5e18d17a-f94c-41f2-8e11-2fbc36705fd3.png)

**Comment by AkshayDubey29** [comment] 2021-11-24 16:05
@ricoberger Where should we put https://github.com/kobsio/kobs/tree/main/pkg/api

**Comment by ricoberger** [comment] 2021-11-24 16:45
> @ricoberger Where should we put https://github.com/kobsio/kobs/tree/main/pkg/api

This shouldn't be necessary, the package is imported by https://github.com/kobsio/app/blob/main/cmd/kobs/kobs.go. If you want to copy it you can place it in https://github.com/kobsio/app/tree/main/pkg and adjust the imports in the kobs.go file.

I'm still not really sure, what you try to achieve, but it sounds like your are copying a lot of code from the [kobsio/kobs](https://github.com/kobsio/kobs) to [kobsio/app](https://github.com/kobsio/app). Maybe for this case it is better to use a fork of https://github.com/kobsio/kobs.

https://github.com/kobsio/app is only intended to add custom plugins and not to modify the core code of kobs or core plugins.

Might this be an option for you or can you explain your requirements a bit more?

**Comment by ricoberger** [comment] 2021-12-24 09:46
I would close the issue for now. If you still have issues please let me know.

**Closed as completed by ricoberger** 2021-12-24 09:46 UTC
Labels: enhancement

**Comment by nshvr** [comment] 2021-12-24 09:59
Thank you for your support
